"""fix favorites

Revision ID: 378e7158fcf6
Revises: 8c32418e36d0
Create Date: 2019-10-22 13:54:42.088858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378e7158fcf6'
down_revision = '8c32418e36d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoriters',
    sa.Column('favoriter_id', sa.Integer(), nullable=True),
    sa.Column('favorited_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorited_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['favoriter_id'], ['user.id'], )
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('favoriter_id', sa.INTEGER(), nullable=True),
    sa.Column('favorited_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['favorited_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['favoriter_id'], ['user.id'], )
    )
    op.drop_table('favoriters')
    # ### end Alembic commands ###
