"""add neighborhood to gig

Revision ID: 7ff987dc51bf
Revises: 0c4425d6ac65
Create Date: 2019-10-23 16:15:18.026661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff987dc51bf'
down_revision = '0c4425d6ac65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gig', sa.Column('neighborhood', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gig', 'neighborhood')
    # ### end Alembic commands ###
